### PR TITLE
Division, remainder, and floating point numbers

### PR DESCRIPTION
**Pull request by arslanarm**
Division operator was implemented just by lowering signed and unsigned operation separately like already written floating point operations.
Floats were implemented pretty easily, when parsing digits if we encounter '.', lookup for next element and if it is a number, we consider it as floating point number. This leads to a problem that '.1' will not count as a float but '0.1' will

### CODE REVIEW

**Comment by arslanarm** [comment]
Initially this pull request was created after encountering the problem with printing the number as a string.
This is the original code that I tried to use
```
import libc as c;
import hades.memory as mem;

def main(): Void {
    print(1);
}

def print[T](value: T): Void where Stringify[T] {
    val s = Stringify[T].to_string(value);
    c.puts(s);
    mem.free(s);
}

trait Stringify[Self] {
    def to_string(self: Self): *mut Byte;
}

implementation Stringify[Int] {
    def to_string(self: Int): *mut Byte {
        val radix = 10;
        val mut count: usize = 0;
        val mut current = self;
        while current > 0 {
            current = current / 10;
            count = count + 1;
        }
        val mut result = mem.allocate[Byte](count);
        current = self;
        val mut i: usize = 0;
        while current > 0 {
            val rem: Byte = 48 + current - (current / 10) * 10;
            current = current / 10;
            *mem.offset_mut(result, i) = rem;
            i = i + 1;
        }
        return result;
    }
}
```

but weirdly enough, I found out that compiling this gives:
`LLVM ERROR: Cannot emit physreg copy instruction`

after that, to make sure that my changes were correct I tried out this code, and everything works fine

```
import libc as c;
import hades.memory as mem;

def main(): Void {
    val self = 1235;
    val mut count: usize = 0;
    val mut current = self;
    while current > 0 {
       current = current / 10;
       count = count + 1;
    }
    val mut result = mem.allocate[Byte](count);
    current = self;
    val mut i: usize = 0;
    while current > 0 {
       val rem = 48 + current - (current / 10) * 10;
       current = current / 10;
       *mem.offset_mut(result, count - 1 - i) = cast(rem);
       i = i + 1;
    }
    c.puts(result);
    mem.free(result);
}

def cast[To, From](from: From): To {
    val copy = from;
    return *pointer_cast[To](&copy);
}
```

**Comment by arslanarm** [comment]
Oh, I actually figured out why `LLVM ERROR: Cannot emit physreg copy instruction` pops up. I removed `: Byte` from the `rem` and casted it using `cast` to u8 and everything works fine

**Comment by arslanarm** [comment]
I am having troubles with understanding how exactly `Analyzer.kt` works. For example why `checkExpression` in the `inferBinaryOperation` are left out, and the returned value is discarded? I am trying to add support for Floats in it but everything seems to work a bit strange

**Comment by dhruvrajvanshi** [comment]
> I am having troubles with understanding how exactly Analyzer.kt works. For example why checkExpression in the inferBinaryOperation are left out, and the returned value is discarded? I am trying to add support for Floats in it but everything seems to work a bit strange

Yeah the current implementation is a bit weird. The reason why checkExpression is called is to simply do the side effect of reporting diagnostics. It's a mess right now honestly 😬

**Comment by dhruvrajvanshi** [comment]
Sorry I missed this PR earlier. I wasn't exactly expecting PRs here 😅 .

**Comment by arslanarm** [comment]
> Sorry I missed this PR earlier. I wasn't exactly expecting PRs here sweat_smile .

No worries, I was just testing out some expressions, but run into compiler errors. I can send you examples where compiler has all the information to infer the type, but fails

**Comment by dhruvrajvanshi** [comment]
Hey, I've merged 2 PRs that handle float literals and float division and modulus.

https://github.com/dhruvrajvanshi/hades-lang/pull/79
https://github.com/dhruvrajvanshi/hades-lang/pull/80

This should be a decent start (look at the test cases to see which cases are handled).

In case there are cases that work unexpectedly, I would suggest adding that to the test suite so that we can track on fixing them and making sure they stay fixed (I routinely do massive refactoring and anything that isn't in the tests will break 😅

**Pull request closed without merging**
